recurly/recurly-client-node

- lib/recurly/BaseClient.js
- test/recurly/BaseClient.test.js
Trying to use a value which contains unencoded strings for a url parameter throws an error:
```js
const account = await client.getAccount("code-benjamin du monde12")
```
```
Unknown Error:  TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
at new ClientRequest (_http_client.js:127:13)
```
We need to encode the url paramters.
> Url Encode Items in interpolatePath

- lib/recurly/BaseClient.js
- test/recurly/BaseClient.test.js
Agent said `recurly-client-node` but we changed the package name to
`recurly` when publishing. This makes sure that we follow the format:
Recurly/$version; $lang
> Fix user agent

- README.md
- docs/index.html
- lib/recurly/BaseClient.js
- lib/recurly/Client.js
- scripts/build
- scripts/format
- scripts/test
- test/recurly/BaseClient.test.js
This removes the constraint of required site-id to initialize a client.
The site can be inferred from the api key. We will be adding ways to
use multiple sites with the same client in the future. This sets us
up so we can do that in a non-breaking way.
> Remove the site-id constraint from Client

- README.md
- lib/recurly.js
Adding an error handling section similar to how we do with other libs: https://recurly-client-python.readthedocs.io/en/latest/#error-handling
I've also exposed the `ApiError` parent class. We'll need to follow up and write some kind of `NetworkError` and wrapper code. right now we are just exposing the source exceptions.
> Add section for err handling

- lib/recurly/BaseClient.js
- test/recurly/BaseClient.test.js
Following up on https://github.com/recurly/recurly-client-node/pull/33
This is not really supported anymore and could be confusing so we're
removing it.
> Remove the site-id parameter in client constructor

- .bumpversion.cfg
- README.md
- package.json
- Implement bump script https://github.com/recurly/recurly-client-node/pull/34
- Add section in README for err handling https://github.com/recurly/recurly-client-node/pull/35
- Remove site id constraint in Client constructor https://github.com/recurly/recurly-client-node/pull/39
- Remove site id constraint https://github.com/recurly/recurly-client-node/pull/33
Technically not a breaking changes, but clients constructors no longer
use the site id. The site will be inferred from the key:
```js
// change your constructors
const client = new recurly.Client(apiKey, siteId);
// to only pass in api key
const client = new recurly.Client(apiKey);
```
> Release 3.0.0-beta.5

- test/recurly.test.js
To test, you can try adding a runtime dep to package.json and running `script/test`. It will fail the tests.
> Do not ever allow runtime deps in this library

- lib/recurly/BaseClient.js
Resolves #51
The client uses the body to delegate which error class to use. But `HEAD` requests do not return with bodies. This ensures there is a fallback procedure to pick an error class. I think this has opened up a deeper question about how we organize and handle errors and we will address this in the next version.
> Pick error class for responses without bodies

- doc/GETTING_STARTED.md
- docs/index.html
It seems like anchor links don't show up in the docs unless you are using h3. So I've changed all these section headers as we want them to be clickable and linkable.
> Anchor links in docs

- lib/recurly/ApiError.js
- lib/recurly/BaseClient.js
- test/recurly/ApiError.test.js
- test/recurly/BaseClient.test.js
Work in progress for now.
https://github.com/recurly/recurly-client-node/pull/63
In the change of Response#body to a string seems, it seems we missed
some cases in the error handling code. We also want to make sure
TransactionErrors have a special case for their different bodies.
> Failure to parse transaction error

- .github_changelog_generator
- CHANGELOG.md
- doc/GETTING_STARTED.md
- docs/index.html
- package-lock.json
- scripts/bump
- scripts/changelog
- scripts/prepare-release
- scripts/release
This implements changelog-generation via https://github.com/github-changelog-generator/github-changelog-generator
I've also added some scripts to facilitate a new release process. When ready to release pending changes:
1. Make sure you are on an up-to-date `master` branch
2. Run `./scripts/prepare-release $part` where `$part` is one of `patch`, `minor`, or `major`. This will create a branch `release-X.Y.Z` (where X.Y.Z is the next version). It will then bump the version and create a commit with the unreleased changelog as the message. It will push that branch as well as create a local tag for X.Y.Z.
3. Review and merge that PR. Change back to master and pull down changes.
4. Run `./scripts/release` to publish the tag and the npm package.
5. Copy-paste output of `release` script for …
> Changelog generation and npm audit

- .bumpversion.cfg
- doc/GETTING_STARTED.md
- lib/recurly/Pager.js
- package.json
Fixes an issue with requesting a list of resources with specific `ids`. The server expects a CSV string of ids, but the api spec specifies that the `ids` should be specified as an array. 
This fix maintains developer happiness by maintaining the ability to specify an array of ids that are transformed to a CSV string when the request is sent to the server.
> Convert Array params to CSV strings

- .bumpversion.cfg
- doc/GETTING_STARTED.md
- docs/index.html
- package-lock.json
- package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.3.0...HEAD)
**Fixed bugs:**
- error TS2504: Type 'AsyncIterator\<Plan, any, undefined\>' must have a '\[Symbol.asyncIterator\]\(\)' method that returns an async iterator. [\#73](https://github.com/recurly/recurly-client-node/issues/73)
- Pager: Use AsyncIterable not AsyncIterator [\#74](https://github.com/recurly/recurly-client-node/pull/74) ([bhelx](https://github.com/bhelx))
> Release 3.3.1

- scripts/prepare-release
- scripts/release
Seems like tags can only be promoted to releases through the UI or API, so I'm using [hub](https://hub.github.com/) now to create the releases. Since we're adding this dependency, i'm also using it to create a PR in `prepare-release`.
> Use hub cli to publish release

- .github_changelog_generator
Newer versions of the `github_changelog_generator` script require that the `user` and `project` parameters be specified
> Updating .github_changelog_generator file for newer versions

- lib/recurly/BaseClient.js
- lib/recurly/Http.js
- lib/recurly/network_errors.js
- test/mock_client.js
- test/recurly/Http.test.js
* Only call JSON.parse when the response content-type is `application/json`
* Better error handling should a load balancer responds with an HTML response instead of JSON
* Set request keep-alive duration to 10 minutes, set connect timeout to 10 seconds
* Safely retry requests when using keep-alive if they return ECONNRESET due to being reset
* Set a request timeout of 60 seconds
* Supports gzip and deflate for response bodies. This allows the client to use less bandwidth and more efficiently paginate through large lists.
> Support gzip responses, improved response handling, keep-alive & timeout settings

- lib/recurly/Client.js
- openapi/api.yaml
Resolves #94 
The optional `params` was not being passed into the `_makeRequest` method for calls where it should be.
> Passing params object into _makeRequest where applicable

- .bumpversion.cfg
- doc/GETTING_STARTED.md
- docs/index.html
- package-lock.json
- package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.5.0...HEAD)
- Passing params object into \_makeRequest where applicable [\#95](https://github.com/recurly/recurly-client-node/pull/95) ([douglasmiller](https://github.com/douglasmiller))
- Updating release script to be uniform across all clients [\#93](https://github.com/recurly/recurly-client-node/pull/93) ([douglasmiller](https://github.com/douglasmiller))
- Thu Mar 26 20:45:12 UTC 2020 Upgrade API version v2019-10-10 [\#92](https://github.com/recurly/recurly-client-node/pull/92) ([bhelx](https://github.com/bhelx))
> Release 3.5.1

- docs/index.html
- lib/recurly/Client.js
Updating the method parameter `params` to `options` to more accurate reflect what the intent of the parameter is. Also updates the incorrect doc comments to better clarify that `options.params` must be an object with individual url parameter keys within.
Resolves #97
> Update method parameter 'params' to 'options' and related doc comments

- lib/recurly/BaseClient.js
- test/recurly/BaseClient.test.js
The optional `options` parameter of `_makeRequest` should only contain the keys `body` or `params` at present. 
This enhancement will validate that only those keys are passed in, as it is easy to accidentally populate query params directly on the `options` object instead of the `options.params` sub-object.
> Validating options passed to _makeRequest

- lib/recurly/BaseClient.js
- lib/recurly/Pager.js
Resolves #105 
There are two bugs that are fixed here.
1. The error handling code was silently failing when a non-2XX response contained a `Content-Type: application/json` header but no body.
2. The `Pager` class was not sending the original params if the `count()` method was called prior to iteration.
> Fixing bugs in the Pager

- lib/recurly/BaseClient.js
- test/recurly/BaseClient.test.js
Adding a validation method that will ensure that path parameters are not empty strings to address issues where a `get_*` operation (`/resources/{resource_id}`) does not get handled by the API as a `list_*` operations (`/resources/`). The validation will also ensure that only approved types are used.
> Ensure that path parameters are not empty strings

- lib/recurly.d.ts
- lib/recurly/Client.js
- openapi/api.yaml
Generated changes to add the `recordExternalTransaction` operation.
> Add recordExternalTransaction operation

- test/recurly/BaseClient.test.js
Updating the test that verifies the generated `User-Agent` to use a regular expression instead of being dependent on the implementation.
> Update User-Agent test to use regex

- .travis.yml
We are also only testing LTS (even numbered) versions.
> Add node 14 to test matrix

- lib/recurly.d.ts
- lib/recurly/Client.js
- lib/recurly/resources/LineItem.js
- lib/recurly/resources/PaymentMethod.js
- lib/recurly/resources/ShippingMethod.js
- lib/recurly/resources/SubscriptionAddOn.js
- openapi/api.yaml
- package-lock.json
* Adds `PaymentMethod#name_on_account` attribute
* Adds `ShippingMethod#accounting_code` attribute
* Adds `SubscriptionAddOn#revenue_schedule_type` attribute
* Adds `state` query param to `Client#list_sites` operation
> Latest Features

- lib/recurly/Http.js
- lib/recurly/Resource.js
This ensures that the HTTP metadata objects are properly documented and show up in the generated docs.
> Document request and response metadata

- lib/recurly/resources.js
- lib/recurly/resources/index.js
- package-lock.json
Resolves #121
Instead of relying on using directory traversal to import resources,
let's generate an index file. This might make it simpler for alternative
import systems (e.g. webpack).
> Explicity import resources rather than dynamic

- lib/recurly/Client.js
- lib/recurly/api_errors.js
- lib/recurly/network_errors.js
Non-breaking update to error classes to give them a hierarchical structure. This will facilitate differentiating between a `ClientError` and a `ServerError` for example.
New error classes have also been added to be parent classes for some existing errors (e.g. `ForbiddenError` is a new class and both `InvalidApiKeyError` and `InvalidPermissionsError` extend it)
> Adding hierarchical errors

- lib/recurly.d.ts
`ApiError` is being moved outside of the `errors` namespace in the typescript declarations to match the client.
> Moving ApiError outside of errors namespace in TS declarations

- lib/recurly.d.ts
- lib/recurly/Client.js
- lib/recurly/resources/Subscription.js
- openapi/api.yaml
- Adds the `state` parameter to the `listAccountCouponRedemptions` operation.
- Adds the `charge` parameter to the `terminateSubscription` operation so that a merchant can choose to not bill a customer for un-billed usage when terminating a subscription
> Latest Changes for 2019-10-10

- lib/recurly.d.ts
Fixing the types of `count()` and `first()` on `Pager<T>` to be a `Promise` to match the existing behavior of the client.
This PR is a generated update from: https://github.com/recurly/recurly-client-node/pull/170
> Fix types of count() and first() on Pager<T>

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- lib/recurly/Http.js
Some updates added to the 3.x client were missed when creating the 4.x client.
> Sync updates not ported from 3.x client 
