.travis.yml, package.json
Adds a travis file for what versions are available and working. Also set it up on travis to run on each PR.
=> Add Travisfile

docs/index.html, lib/recurly/Client.js, lib/recurly/resources/AccountAcquisitionCost.js, lib/recurly/resources/BillingInfoPaymentMethod.js, lib/recurly/resources/BillingInfoUpdatedBy.js, lib/recurly/resources/Coupon.js, lib/recurly/resources/CouponDiscountTrial.js, lib/recurly/resources/FraudInfo.js, lib/recurly/resources/InvoiceAddress.js, lib/recurly/resources/LineItem.js, lib/recurly/resources/Plan.js, lib/recurly/resources/PlanHostedPages.js, lib/recurly/resources/TransactionPaymentGateway.js, lib/recurly/resources/TransactionPaymentMethod.js
Ran generator to update library
=> V3 Update v2018-08-09

docs/index.html, lib/recurly.js, lib/recurly/ApiError.js, lib/recurly/BaseClient.js, lib/recurly/Caster.js, lib/recurly/Client.js, lib/recurly/api_errors.js, lib/recurly/resources/AddOn.js, lib/recurly/resources/LineItem.js, lib/recurly/resources/Plan.js, lib/recurly/utils.js
We need typed errors and a hierarchy of error types like we have in the other libraries.
=> Error hierarchy

package-lock.json, package.json
Bumps test packages. These are only used in tests so it should be fine as long as the tests pass.
=> Bump test packages

package.json
* Latest 2018-08-09 changes (including purchases) https://github.com/recurly/recurly-client-node/pull/17
* Casting improvements and strict-mode testing: https://github.com/recurly/recurly-client-node/pull/16
* Encode params: https://github.com/recurly/recurly-client-node/pull/13
* Fix the user agent: https://github.com/recurly/recurly-client-node/pull/12
Resources are now being recursively cast correctly for every object. Some properties may now be returning a "typed" object rather than a plain JS obj. This likely won't affect the interface unless you were peeking at those types and expecting them to be something specific.
=> 3.0.0.beta.3

lib/recurly/Caster.js, test/recurly/Caster.test.js
Fixes problem as described in #19 by @romeroadrian. Also added some more tests cases for good measure.
=> Fix castRequest for arrays

lib/recurly/resources/AccountAcquisition.js, lib/recurly/resources/BillingInfo.js, lib/recurly/resources/CouponDiscount.js, lib/recurly/resources/Transaction.js, lib/recurly/resources/TransactionError.js
* Latest v2018-08-09 updates from the generator.
* Fixes some plain `Object`s that should have had types.
=> Latest v2018-08-09 updates

README.md, package.json
* Fix `castRequest` for primitive arrays (and other edge cases) #20 (Issue #19)
* Fix documentation builder https://github.com/recurly/recurly-client-node/commit/864b55c32be5290d5a4b647af48f15ab10d7dedb
* Latest changes for 2018-08-09 (fixes some improperly untyped relations) https://github.com/recurly/recurly-client-node/pull/21
=> Bump 3.0.0-beta.4

README.md, docs/index.html, lib/recurly/ApiError.js, lib/recurly/BaseClient.js, lib/recurly/Caster.js, lib/recurly/Client.js, lib/recurly/Http.js, lib/recurly/Pager.js, lib/recurly/Resource.js, lib/recurly/resources.js, lib/recurly/resources/BillingInfo.js, lib/recurly/resources/CouponDiscount.js, lib/recurly/resources/ErrorMayHaveTransaction.js, package.json, test/recurly/Caster.test.js, test/recurly/Resources.test.js
Provide an interface for exposing http request and response metadata.
Technically has breaking changes as previously void methods now return instances of Empty.
=> Expose Request and Response metadata

README.md
Document use of webhooks. For now, we are recommending people parse and manage them themselves.
=> Document use of webhooks

README.md
`async myFunc() ... ` was missing the word `function`
=> Update some typos in the readme

package.json
* Add repository key
* Change authorship to DX team
=> package.json needs repository key

lib/recurly/BaseClient.js, lib/recurly/Http.js, package-lock.json, package.json, scripts/test, test/mock_client.js, test/mock_resources.js, test/recurly.test.js, test/recurly/BaseClient.test.js, test/recurly/Http.test.js, test/recurly/Pager.test.js
92% coverage so far. Still some improvements we can make to the patterns.
=> More test coverage

docs/index.html, lib/recurly/BaseClient.js, lib/recurly/Caster.js, lib/recurly/Client.js, lib/recurly/Http.js, lib/recurly/Pager.js, lib/recurly/resources/BinaryFile.js, lib/recurly/resources/Item.js, lib/recurly/resources/LineItem.js, lib/recurly/resources/Pricing.js, openapi/api.yaml, test/recurly/BaseClient.test.js, test/recurly/Caster.test.js, test/recurly/Http.test.js, test/recurly/Pager.test.js
- Adds capability to support `application/pdf` responses
- Adds `Item` support
=> Generated Updates for API version v2019-10-10

.bumpversion.cfg, doc/GETTING_STARTED.md, docs/index.html, lib/recurly/Http.js, package-lock.json, package.json
Updating responseEncoding function to provide default value when contentType is undefined
=> Release 3.1.1 (Bug fix for TypeError in responseEncoding function)

.bumpversion.cfg, doc/GETTING_STARTED.md, package.json
*  Allow object attributes #65
=> Release 3.2.0

test/recurly/BaseClient.test.js
Was showing @joannasese the V3 node client and identifying missing
tests with coverage reports. We added this spec.
=> Adding missing TransactionError test

doc/GETTING_STARTED.md, docs/index.html, lib/recurly.d.ts, lib/recurly/Client.js, openapi/api.yaml, package-lock.json, package.json, scripts/build, scripts/clean, scripts/test
Adds typescript definitions. We are shipping with the library currently. Resolves #29
Stuff to investigate for later:
1. Specify / name the request types
2. Add enum values where available instead of using String
3. Publish separately from the code (probably under DefinitelyTyped)
=> Typescript definitions

lib/recurly.d.ts
=> Pager: Use AsyncIterable not AsyncIterator

docs/index.html, lib/recurly.d.ts, lib/recurly/api_errors.js, lib/recurly/resources/Account.js, lib/recurly/resources/AccountAcquisition.js, lib/recurly/resources/AccountBalance.js, lib/recurly/resources/Coupon.js, lib/recurly/resources/CouponMini.js, lib/recurly/resources/CreditPayment.js, lib/recurly/resources/Invoice.js, lib/recurly/resources/Item.js, lib/recurly/resources/LineItem.js, lib/recurly/resources/PaymentMethod.js, lib/recurly/resources/Subscription.js, lib/recurly/resources/SubscriptionAddOn.js, lib/recurly/resources/SubscriptionChange.js, lib/recurly/resources/Transaction.js, openapi/api.yaml
* More documentation
* `Account#has_*` flag attributes
* Include `RateLimitedError`
* Gateway Token Support
=> Latest v2019-10-10 Changes

docs/index.html, lib/recurly.d.ts, lib/recurly/Client.js, lib/recurly/resources/AddOn.js, lib/recurly/resources/AddOnMini.js, lib/recurly/resources/ItemMini.js, lib/recurly/resources/PaymentMethod.js, openapi/api.yaml
* convert trial endpoint
* item-backed add-ons
* IBAN billing info
=> Latest generated changes for v2019-10-10

.bumpversion.cfg, doc/GETTING_STARTED.md, docs/index.html, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.3.1...HEAD)
- Latest generated changes for v2019-10-10 [\#81](https://github.com/recurly/recurly-client-node/pull/81) ([bhelx](https://github.com/bhelx))
- Use new webhooks doc link [\#80](https://github.com/recurly/recurly-client-node/pull/80) ([bhelx](https://github.com/bhelx))
- Latest v2019-10-10 Changes [\#78](https://github.com/recurly/recurly-client-node/pull/78) ([bhelx](https://github.com/bhelx))
- Small tweaks to docs [\#77](https://github.com/recurly/recurly-client-node/pull/77) ([bhelx](https://github.com/bhelx))
- Use hub cli to publish release [\#76](https://github.com/recurly/recurly-client-node/pull/76) ([bhelx](https://github.com/bhelx))
- Release 3.3.1 …
=> Release 3.4.0

.bumpversion.cfg, doc/GETTING_STARTED.md, docs/index.html, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.4.0...HEAD)
- Updating .github\_changelog\_generator file for newer versions [\#88](https://github.com/recurly/recurly-client-node/pull/88) ([douglasmiller](https://github.com/douglasmiller))
- Fri Mar 20 17:44:13 UTC 2020 Upgrade API version v2019-10-10 [\#87](https://github.com/recurly/recurly-client-node/pull/87) ([douglasmiller](https://github.com/douglasmiller))
- Bump acorn from 6.0.4 to 6.4.1 [\#85](https://github.com/recurly/recurly-client-node/pull/85) ([dependabot[bot]](https://github.com/apps/dependabot))
- Add request for stack trace in issue report [\#84](https://github.com/recurly/recurly-client-node/pull/84) ([bhelx](https://github.com/bhelx))
- Generate and commit changelog …
=> Release 3.4.1

.bumpversion.cfg, doc/GETTING_STARTED.md, docs/index.html, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.4.1...HEAD)
- Support gzip responses, improved response handling, keep-alive & timeout settings [\#90](https://github.com/recurly/recurly-client-node/pull/90) ([isaachall](https://github.com/isaachall))
=> Release 3.5.0

docs/index.html, lib/recurly.d.ts, lib/recurly/Client.js, openapi/api.yaml, package-lock.json
* Adds `deactivate_coupon` endpoint
=> Thu Mar 26 20:45:12 UTC 2020 Upgrade API version v2019-10-10

lib/recurly.d.ts, lib/recurly/Client.js, lib/recurly/resources/AddOn.js, lib/recurly/resources/SubscriptionAddOn.js, lib/recurly/resources/SubscriptionAddOnTier.js, lib/recurly/resources/Tier.js, openapi/api.yaml, package-lock.json
* Add `optional` to AddOnUpdate
* Adding quantity based pricing support
=> Tue Apr 14 20:25:06 UTC 2020 Upgrade API version v2019-10-10

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.5.1...HEAD)
- Tue Apr 14 20:25:06 UTC 2020 Upgrade API version v2019-10-10 [\#103](https://github.com/recurly/recurly-client-node/pull/103) ([bhelx](https://github.com/bhelx))
- Validating options passed to \_makeRequest [\#101](https://github.com/recurly/recurly-client-node/pull/101) ([douglasmiller](https://github.com/douglasmiller))
- Included the to-be released changes in the changelog [\#102](https://github.com/recurly/recurly-client-node/pull/102) ([douglasmiller](https://github.com/douglasmiller))
- Remove docs from tracking and use github actions [\#100](https://github.com/recurly/recurly-client-node/pull/100) ([bhelx](https://github.com/bhelx))
- …
=> Release 3.6.0

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.6.0...HEAD)
- Add recordExternalTransaction operation [\#109](https://github.com/recurly/recurly-client-node/pull/109) ([bhelx](https://github.com/bhelx))
**Fixed bugs:**
- Clarification listInvoices on params; limit does not seem to be working [\#105](https://github.com/recurly/recurly-client-node/issues/105)
- Fixing bugs in the Pager [\#106](https://github.com/recurly/recurly-client-node/pull/106) ([douglasmiller](https://github.com/douglasmiller))
=> Release 3.7.0

lib/recurly.d.ts, lib/recurly/Client.js, lib/recurly/resources/Plan.js, lib/recurly/resources/Transaction.js, lib/recurly/resources/index.js, openapi/api.yaml
- Adds `create_shipping_method` operation.
- Adds `update_shipping_method` operation.
- Adds `deactivate_shipping_method` operation.
- Adds `updatedAt ` attribute to `Transaction`.
- Adds `allowAnyItemOnSubscriptions ` attribute to `Plan`.
- Adds `trialRequiresBillingInfo ` attribute to `Plan`.
=> Mon Jun 29 17:12:50 UTC 2020 Upgrade API version v2019-10-10

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.8.1...HEAD)
- Mon Jun 29 17:12:50 UTC 2020 Upgrade API version v2019-10-10 [\#126](https://github.com/recurly/recurly-client-node/pull/126) ([douglasmiller](https://github.com/douglasmiller))
- Fix the api-errors doc link [\#123](https://github.com/recurly/recurly-client-node/pull/123) ([bhelx](https://github.com/bhelx))
=> Release 3.9.0

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.9.0...HEAD)
- Wed Jul  1 02:09:59 UTC 2020 Upgrade API version v2019-10-10 [\#128](https://github.com/recurly/recurly-client-node/pull/128) ([douglasmiller](https://github.com/douglasmiller))
=> Release 3.10.0

openapi/api.yaml
- Updates openapi specification
=> Mon Jul  6 14:52:04 UTC 2020 Upgrade API version v2019-10-10

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.10.0...HEAD)
- Add request types to TS definitions [\#134](https://github.com/recurly/recurly-client-node/pull/134) ([bhelx](https://github.com/bhelx))
- Adding hierarchical errors [\#132](https://github.com/recurly/recurly-client-node/pull/132) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 \(usage, measured units, etc\) [\#138](https://github.com/recurly/recurly-client-node/pull/138) ([bhelx](https://github.com/bhelx))
- Running npm audit fix [\#133](https://github.com/recurly/recurly-client-node/pull/133) ([bhelx](https://github.com/bhelx))
- Mon Jul  6 14:52:04 UTC 2020 Upgrade API version v2019-10-10 …
=> Release 3.11.0

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.13.0...HEAD)
- Latest Changes for 2019-10-10 \(Automated Exports, additional resource data attributes\) [\#147](https://github.com/recurly/recurly-client-node/pull/147) ([douglasmiller](https://github.com/douglasmiller))
=> Release 3.14.0

lib/recurly.d.ts, lib/recurly/Client.js, openapi/api.yaml
* Adds `restoreCoupon` operation.
=> Mon Oct 19 20:40:44 UTC 2020 Upgrade API version v2019-10-10

lib/recurly.d.ts, lib/recurly/Client.js
Updating Typescript declarations to include the `errors` namespace.
Resolves: https://github.com/recurly/recurly-client-node/issues/150
=> Updating typescript declarations

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.15.0...HEAD)
- Latest Changes for 2019-10-10 \(Wallet, Item Coupons\) [\#158](https://github.com/recurly/recurly-client-node/pull/158) ([douglasmiller](https://github.com/douglasmiller))
- Moving ApiError outside of errors namespace in TS declarations [\#162](https://github.com/recurly/recurly-client-node/pull/162) ([douglasmiller](https://github.com/douglasmiller))
- Updating typescript declarations [\#160](https://github.com/recurly/recurly-client-node/pull/160) ([douglasmiller](https://github.com/douglasmiller))
- Correct @param, Pager.eachPage types [\#159](https://github.com/recurly/recurly-client-node/pull/159) …
=> Release 3.16.0

doc/GETTING_STARTED.md
Revised readme to call out Header case sensitivity
=> Update getting-started guide with memo about headers

lib/recurly.d.ts, lib/recurly/Client.js, openapi/api.yaml
- Adds `tax_identifier` and `tax_identifier_type` to the `BillingInfoCreate` TypeScript request interface.
- Removes `add_ons` from the `PlanUpdate` TypeScript request interface due to being unsupported.
=> Latest Changes for 2019-10-10 (tax_identifier / tax_identifier_type)

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.18.0...HEAD)
- Latest Changes for 2019-10-10 [\#178](https://github.com/recurly/recurly-client-node/pull/178) ([douglasmiller](https://github.com/douglasmiller))
=> Release 3.19.0

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/3.19.0...HEAD)
The 4.x major version of the client pairs with the `v2021-02-25` API version. This version of the client and the API contain breaking changes that should be considered before upgrading your integration.
All changes to the core API are documented in the [Developer Portal changelog](https://developers.recurly.com/api/changelog.html#v2021-02-25---current-ga-version)
- Classify unexpected error responses from Recurly API via an HTTP status code mapping provided in `recurly.errors.ERROR_MAP`. Status code `502` now maps to `recurly.errors.BadGatewayError`.  [#136]
- Replace `recurly.errors.ValidationError` with `recurly.errors. UnprocessableEntityError`.  [#136]
- Accept `params`, `headers` though an options …
=> Release 4.0.0

.bumpversion.cfg, doc/GETTING_STARTED.md, package-lock.json, package.json
[Full Changelog](https://github.com/recurly/recurly-client-node/compare/4.0.0...HEAD)
- Generated Latest Changes for v2021-02-25 [\#189](https://github.com/recurly/recurly-client-node/pull/189) ([recurly-integrations](https://github.com/recurly-integrations))
- Sync updates not ported from 3.x client  [\#185](https://github.com/recurly/recurly-client-node/pull/185) ([douglasmiller](https://github.com/douglasmiller))
=> Release 4.0.1

lib/recurly.d.ts, lib/recurly/resources/Tier.js, openapi/api.yaml, package-lock.json, package.json
Adds `usagePercentage` to the `Tier` resource.
=> Generated Latest Changes for v2021-02-25 (Usage Percentage on Tiers)
